config/routes.rb
Rails.application.routes.draw do
  get 'experiments/page1'

  get 'experiments/page2'

  get 'experiments/page3'

  get 'pages/batman'

  get 'pages/superman'

  get 'pages/batman_vs_superman'

  post 'pages/save_voto'

  root 'pages#batman_vs_superman'

end

app/models/voto.rb
class Voto < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
	layout 'bootstrap'
  def page1
  	
  end

  def page2
  end

  def page3
  end
  
  private
  def var
  	@counter =100
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def batman
  end
  def superman
  end	
  def batman_vs_superman
  end	

  def save_voto
    if params[:heroe].present? && params[:email].present?
      Voto.create(
        heroe: params[:heroe],
        email: params[:email],
       
        )

      redirect_to pages_batman_vs_superman_path, notice: "voto"

    else
      flash[:alert] = "Complete todos los datos"
      render :batman_vs_superman
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/experiments/page1.html.erb
<script>var = 200</script>


<%= javascript_include_tag 'countdown'%>
<%= yield %>
<h1>Experiments#page1</h1>
<p>Find me in app/views/experiments/page1.html.erb</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/experiments/page2.html.erb
<h1>Experiments#page2</h1>
<p>Find me in app/views/experiments/page2.html.erb</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/experiments/page3.html.erb
<%= stylesheet_link_tag 'page3', media: 'all' %>
<%= yield  %>

<h1>Experiments#page3</h1>
<p>Find me in app/views/experiments/page3.html.erb</p>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/bootstrap.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheroes</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
 <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script> 
</head>
<body  class="<%= params[:controller]  %>">
<%= render partial: "shared/navbar" %>
<%= yield %>

</body>
</html>

app/views/pages/batman.html.erb
<h1>Pages#batman</h1>
<p>Find me in app/views/pages/batman.html.erb</p>
<script type="text/javascript">
  $.backstretch("http://i.kinja-img.com/gawker-media/image/upload/s--_cCfXp_D--/1370862899782781508.png");
</script>

<h1>I am Batman</h1>

app/views/pages/batman_vs_superman.html.erb
<div class="container">
<div style="width: 50%; float:left">
	<div class="heroe_container">
	   	
	<button><%= link_to 'superman', pages_superman_path %></button>
		
		<%= form_tag pages_save_voto_path, method: "post" do %>
		<div class="form-group">
			<%= label_tag :heroe, "Nombre:" %>
			<%= text_field_tag :heroe, params[:heroe], class: "form-control" %>
		</div>

		<div class="form-group">
			<%= label_tag :email, "email:" %>
			<%= text_field_tag :email, params[:email], class: "form-control" %>
		</div>
		<div class="form-group">
			<%= submit_tag "Enviar", class: "btn btn-success" %>
		</div>

		<% end %>
		<img src="https://i.kinja-img.com/gawker-media/image/upload/ltjuhuqmei36srteldly.jpg">
	</div>
   
</div>

<div style="width: 50%; float:right">
	<div class="heroe_container">
		<button><%= link_to 'batman', pages_batman_path %></button>
		

		<%= form_tag pages_save_voto_path, method: "post" do %>
		<div class="form-group">
			<%= label_tag :heroe, "Nombre:" %>
			<%= text_field_tag :heroe, params[:heroe], class: "form-control" %>
		</div>

		<div class="form-group">
			<%= label_tag :email, "email:" %>
			<%= text_field_tag :email, params[:email], class: "form-control" %>
		</div>
		<div class="form-group">
			<%= submit_tag "Enviar", class: "btn btn-success" %>
		</div>

		<% end %>

	   <img src="http://jumphawk.jovemnerd.com.br/wp-content/uploads/DSC5762-AO5.jpg">
   </div>
</div>
</div>

app/views/pages/superman.html.erb
<h1>Pages#batman</h1>
<p>Find me in app/views/pages/batman.html.erb</p>
<script type="text/javascript">
  $.backstretch("http://cdn.playbuzz.com/cdn/8ff306c2-e5d4-4974-9151-5118192add5d/f040fb43-6aa8-43c0-8ba8-15f997347f15.jpg");
</script>

<h1>This looks like a job for Superman</h1>

app/views/shared/_navbar.html.erb
<ul class="nav nav-pills">
  <li role="presentation"><%= link_to 'page1', experiments_page1_path %></li>
  <li role="presentation"><%= link_to 'page2',experiments_page2_path  %></li>
  <li role="presentation"><%= link_to 'page3',experiments_page3_path  %></li>
</ul>